[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "dist"

# API 프록시
[[redirects]]
  from = "/api/*"
  to = "http://3.37.127.247:8080/:splat"
  #to = "https://afk-mock.onrender.com/:splat"
  status = 200
  force = true

# S3 이미지 프록시
[[redirects]]
  from = "/proxy-image/*"
  to = "https://arc-risk-finder.s3.ap-northeast-2.amazonaws.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/proxy-image/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
